### ISSUE TITLE
Sell strategy example refers to BuySell in the Price Feeds section 

### ISSUE THREAD

**Issue by MarchHare-MU** [stellar/kelp#313]
I've read through the sell strategy example (ICO Sale) a number of times, but to be honest I find it quite confusing and in the Price Feeds section, it refers to the BuySell?

https://github.com/stellar/kelp/blob/master/examples/walkthroughs/trader/sell.md

In the guide it says that the final price is calculated by dividing A by B, however when we use 2 data feeds, for example A - fiat and B - exchange, the offer placed on the dex isn't A/B.

Is this an error in the documentation?

**Comment by nikhilsaraf** [comment]
@MarchHare-MU the offer placed on the dex would also consider the **spread** from the `LEVELS`.

The idea behind the `sell` strategy is to have a one-sided buysell strategy -- i.e. if you only wanted to sell a specific token rather than market-making that specific market.

I fixed the documentation to say `Sell` instead of `BuySell`

**Comment by nikhilsaraf** [comment]
@MarchHare-MU closing this issue. If there's more questions regarding this please feel free to open a new issue.
