### ISSUE TITLE
CANNOT GET /exchanges/binance

### ISSUE THREAD

**Issue by BouweCeunen** [stellar/kelp#420]
## Describe the bug
The bot does a call to /exchanges on ccxt-rest. This results in an error `CANNOT GET /exchanges/binance`.

## Expected behavior
I think the correct behavior in this situation is for the bot to do a call to `/exchange` because ccx has en `/exchange` endpoint and not a `/exchanges` endpoint.

## Frequency
The frequency is always.

## Steps To Reproduce
// A concise description of the **steps to reproduce the buggy behavior** along with screenshots wherever applicable:

Here are the steps to reproduce the issue (see attachments in section below):
1. Clone ccxt-rest repository
2. Build docker container
3. Start docker container of ccxt
4. Do a call to `/exchanges/binance` => will result in CANNOT GET /exchanges/binance
...

## Possible Solution
Change https://github.com/stellar/kelp/blob/a6ffc8c770b03999c58fd2f589b58622fa80ac00/support/sdk/ccxt.go#L65 to `exchange`.

## Your Environment
cli version: master:v1.9.0-2-g6c9411cb
gui version: v1.0.0-rc1
git branch: master
git hash: 6c9411cbd94e1c652116652eaa0e0aa40f215d74
build date: 20200509T224154Z
env: dev
GOOS: linux
GOARCH: arm

## Context
I am unable to start Kelp.

## Attachments
```bash
/ # curl http://localhost:3000/exchanges/binance
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /exchanges/binance</pre>
</body>
</html>
```

**Comment by nikhilsaraf** [comment]
@BouweCeunen that happens when you use the newer version of ccxt-rest. Version 0.0.4 is the recommended version of ccxt-rest to be used with Kelp.

We will be upgrading the version of ccxt-rest that we depend on at a later date, for now I’d recommend using the version mentioned above.

Here’s more info about using ccxt-rest with kelp:
https://github.com/stellar/kelp#using-ccxt

If this solution resolves your issue please feel free to close this ticket.
