### ISSUE TITLE
Copy of Kelp

### ISSUE THREAD

**Issue by strepio** [stellar/kelp#641]

**Comment by nikhilsaraf** [comment]
@strepio can you please elaborate on the de tails of this issue please?

**Comment by strepio** [comment]
Hey I'm new to this and I'm trying to code something for manual bot trading and also learn git at the same time. Sorry if I messed something up.

**Comment by nikhilsaraf** [comment]
@strepio nothing messed up. welcome to the Kelp repo!
Creating an issue is usually done when you want to report problems or request features in the project. Feel free to ask anything else you want here, otherwise you can "close" this issue with the button at the bottom. I'm happy to answer any questions you have about the project.

**Comment by nikhilsaraf** [comment]
closing this out for now, please feel free to open a new issue if needed.
