### ISSUE TITLE
Unable to Continue/Accept Terms

### ISSUE THREAD

**Issue by Squiji** [stellar/kelp#693]
On first run after ./Kelp, unable to Accept/Continue Terms
![Screenshot from 2021-04-19 22-12-56](https://user-images.githubusercontent.com/50003357/115341330-436a4300-a15d-11eb-96a3-2c6bee69dd47.png)

'Kelp GUI (beta) Legal Disclaimer Screen'

1366x768 pixels

**Comment by nikhilsaraf** [comment]
thank you for filing this issue.

This has been fixed in the latest master branch ([here](https://github.com/stellar/kelp/commit/86214e85dd06557792bc243d1143638c50a6b1eb)) but not yet uploaded as a precompiled binary. Will try and upload as a precompiled binary soon and add a comment here once that's done.

**Comment by CharlieOxendine** [comment]
I opened up the developer tools and deleted the list and it shrank it enough to let me accept. Just as a temporary solution

**Comment by nikhilsaraf** [comment]
marking as closed since it's fixed in [this commit](https://github.com/stellar/kelp/commit/86214e85dd06557792bc243d1143638c50a6b1eb). I will be doing a release in July and will include this fix in that release.
